### ISSUE TITLE
Emails on New Issues

### ISSUE THREAD

**Issue by wbrawner** [F43nd1r/Acrarium#27]
It would be nice to be able to configure email settings to get alerts from Acrarium. I can think of a few use cases where this might be useful:

- a new issue is reported
- an issue marked as resolved shows up in a new release (a regression)
- a massive number of issues suddenly are reported (e.g. 20% more than usual)
- a weekly summary of the top issues

**Comment by F43nd1r** [comment]
Currently looking into this.
> a new issue is reported

This one is easy. However it can get spammy really fast, so I don't think many people need this.

>an issue marked as resolved shows up in a new release (a regression)

I'm not sure the current database structure supports this. A bug can have stacktraces from multiple versions, and I don't know in which version it was marked as solved.

> a massive number of issues suddenly are reported (e.g. 20% more than usual)

It is quite hard to define what is 'usual'. E.g. if I compared the last hour to the 5 hours before that, there might just be more reports because it was night. If you have nice ideas how to approach this, let me know.

> a weekly summary of the top issues

Weekly summary is easy. How would you define 'top issues'?

**Comment by wbrawner** [comment]
> > a new issue is reported
> 
> This one is easy. However it can get spammy really fast, so I don't think many people need this.

Right, my idea was that if an issue that hasn't been seen before (based on the hash of the stacktrace or something) is reported, _then_ it can be emailed to you. I don't want an email for every time an error is reported either, just if it's something that Acrarium hasn't seen before.

> > an issue marked as resolved shows up in a new release (a regression)
>
> I'm not sure the current database structure supports this. A bug can have stacktraces from multiple versions, and I don't know in which version it was marked as solved.

Yeah, it would most likely require not only marking an issue as solved but solved as of x version. Didn't know how big of a change it would be but I figured I'd suggest it anyways

> > a massive number of issues suddenly are reported (e.g. 20% more than usual)
>
> It is quite hard to define what is 'usual'. E.g. if I compared the last hour to the 5 hours before that, there might just be more reports because it was night. If you have nice ideas how to approach this, let me know.

I don't think an hourly check would be good, maybe a daily check at most? So you could compare the average number of issues over the past 7 days, and see if the issues reported within the last 24 hours more or less align with the averages of the past 7 days. I.e. if you see that you're getting around 50 issues per day for the past 7 days, and suddenly within the last 24 hours you have 100 new issues, that should trigger an alert that maybe something is wrong. 

> a weekly summary of the top issues
>
> Weekly summary is easy. How would you define 'top issues'?

For top issues I would just say the 5 most commonly reported in that week. If there were no issues reported in the week, then it could also send out a congratulatory message that everything appears to be working correctly.

**Comment by F43nd1r** [comment]
Just to get on one level, I'm using three terms here:
 - a report is everything a user sent
- a stacktrace is a set of reports which have the same text (so the actual stacktrace) and version.
- a bug is a set of stacktraces which have been merged either by the automatic tool or by a user. It only holds the "solved" value.

>Right, my idea was that if an issue that hasn't been seen before (based on the hash of the stacktrace or something) is reported, then it can be emailed to you. I don't want an email for every time an error is reported either, just if it's something that Acrarium hasn't seen before.

Do you want an email for each new bug, or each new stacktrace?

> Yeah, it would most likely require not only marking an issue as solved but solved as of x version. Didn't know how big of a change it would be but I figured I'd suggest it anyways

solved as of version x sounds like a good thing. would require somehow that you can create a version (right now they are created as soon as the first report for the version comes in).

>I don't think an hourly check would be good, maybe a daily check at most? So you could compare the average number of issues over the past 7 days, and see if the issues reported within the last 24 hours more or less align with the averages of the past 7 days. I.e. if you see that you're getting around 50 issues per day for the past 7 days, and suddenly within the last 24 hours you have 100 new issues, that should trigger an alert that maybe something is wrong.

I agree that for this "massive reports"-metric daily or weekly makes more sense than hourly, but in general hourly (instead of instant) mails for e.g. new bugs would make sense.

> For top issues I would just say the 5 most commonly reported in that week.

Sounds like a number that should be configurable.

> If there were no issues reported in the week, then it could also send out a congratulatory message that everything appears to be working correctly.

I'd personally dislike that, but sure it could be an option.

**Comment by wbrawner** [comment]
Apologies for the delay, I had a busy couple of months :/ 

> Do you want an email for each new bug, or each new stacktrace?

I think it makes more sense per-bug, as per-stacktrace might get overly noisy.

I'd be happy to help out with this too if needed/wanted

**Comment by F43nd1r** [comment]
You can have a look at the current state in #33. I developed this over a month ago, and didn't finish because of lacking time. This is in an intermediate state, I don't know exactly in which state I left it, it might not even run.

If you want to finish that, I can assist if you don't understand my code.
